version: '3.8'

services:
  ml-pipeline:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: geoai_ml_pipeline
    volumes:
      - ./data:/data
    env_file:
      - .env
    command: python main.py --help
